# Generated by Django 2.2.5 on 2021-09-12 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=4)),
                ('amount', models.IntegerField()),
                ('time', models.IntegerField()),
                ('maxSpeed', models.IntegerField()),
                ('meanSpeed', models.IntegerField()),
                ('drunkenness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('satisfaction', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('alcohol', models.CharField(blank=True, choices=[('L', 'Liquor'), ('B', 'Beer'), ('S', 'Soju'), ('W', 'Wine'), ('M', 'Makgeolli')], max_length=10)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('who', models.CharField(blank=True, choices=[('FR', 'Friend'), ('FA', 'Family'), ('BU', 'Business'), ('AL', 'Alone'), ('SO', 'Someone')], max_length=10)),
                ('surveyCheck', models.BooleanField(default=False)),
            ],
        ),
    ]
