# Generated by Django 2.2.5 on 2021-09-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('sojuAbility', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='alldata',
            name='alcohol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='who',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
