# Generated by Django 2.2.5 on 2021-09-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_auto_20210925_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='maxSpeed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='meanSpeed',
            field=models.FloatField(),
        ),
    ]
